### ISSUE TITLE
Allow pickup only while sneaking

### ISSUE THREAD

**Issue by csampersand** [Draylar/item-pickup-customization#2]
An option for this would be amazing

**Comment by csampersand** [comment]
you're amazing

**Comment by Draylar** [comment]
Pushing a 1.1.0 release now with a revamped config file. Here's an example:
```
{
  "allowCollisionPickup": true,
  "allowClickPickup": false,
  "collisionRequiresShift": false,
  "clickRequiresShift": false
}
```
The two new options at the bottom add this capability, so you can pick and match what you want. You can delete your current config file and it will automagically regenerate.

**Comment by Draylar** [comment]
Up on [GitHub](https://github.com/Draylar/item-pickup-customization/releases/tag/1.1.0-1.15.2) and [CurseForge](https://www.curseforge.com/minecraft/mc-mods/item-pickup-customization/files/2947391).
